name: CI/CD – Build & Deploy to Cloud Run

on:
  push:
    branches: [ video-audio-pipeline ]

env:
  IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/video-processor:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: video-audio-pipeline

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: video-audio-pipeline

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy video-processor-service \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
